# -*- coding: utf-8 -*-
"""Fruits_vegetables_model_converting_images_to_arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FdqLHcm5EF8BbxsJDvI62KblgDvsPhL
"""

#import tensorflow as tf
import cv2
from tqdm import tqdm
#import matplotlib.pyplot as plt
import os

"""importing necessary libraries"""

#! pip install kaggle
#! mkdir ~/.kaggle
#! cp kaggle.json ~/.kaggle/
#! chmod 600 ~/.kaggle/kaggle.json

"""connecting to kaggle courtesy-[this website](https://https://www.analyticsvidhya.com/blog/2021/06/how-to-load-kaggle-datasets-directly-into-google-colab/
)
"""

#!kaggle datasets download raghavrpotdar/fresh-and-stale-images-of-fruits-and-vegetables

"""dataset from [kaggle](https://www.kaggle.com/datasets/raghavrpotdar/fresh-and-stale-images-of-fruits-and-vegetables"""

#! unzip fresh-and-stale-images-of-fruits-and-vegetables.zip

#img_array = cv2.imread("/content/stale_banana/translation_Screen Shot 2018-06-12 at 9.03.51 PM.png")

#img_array2 = cv2.imread("/content/stale_orange/rotated_by_75_Screen Shot 2018-06-12 at 11.22.41 PM.png")
#plt.imshow(img_array)
#plt.show()

#resolution=(45,45)
#img_array = cv2.resize(img_array,resolution)
#plt.imshow(img_array)
#plt.show()

#img_array = cv2.imread("/content/stale_orange/rotated_by_75_Screen Shot 2018-06-12 at 11.22.41 PM.png")
#plt.imshow(img_array)
#plt.show()

resolution=(45,45)
#img_array = cv2.resize(img_array,resolution)
#plt.imshow(img_array)
#plt.show()

#img_array = cv2.imread("/content/fresh_tomato/DSCN4068.jpg_0_1176.jpg")
#plt.imshow(img_array)
#plt.show()

#resolution=(45,45)
#img_array = cv2.resize(img_array,resolution)

#plt.imshow(img_array)
#plt.show()

#img_array = cv2.imread("/content/fresh_banana/Screen Shot 2018-06-12 at 10.00.12 PM.png")
#plt.imshow(img_array)
#plt.show()

#resolution=(45,45)
#img_array = cv2.resize(img_array,resolution)
#plt.imshow(img_array)
#plt.show()

#Tried different resolutions,settled at 45*45

""" **Labels** Fresh apple-01 Fresh bannana-02 Fresh bitter guard-03 fresh capsicum-04 fresh orange-05 fresh tomato-06
Stale apple-7 Stale banana-8 Stale bitter guard-9 stale capsicum-10 Stale orange-11 Stale tomato-12
old
new subtract one from each ie
Fresh apple-0 fresh banana -1 and so on
"""

path="/home/shreyas/fresh_apple"
training_data=[]
resolution=(45,45)
from rembg import remove
for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    
    training_data.append([new_array,1])
  except:
    pass
path="/home/shreyas/fresh_banana"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,2])
  except:
    pass    
path="/home/shreyas/fresh_bitter_gourd"
for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,3])
  except:
    pass
path="/home/shreyas/fresh_capsicum"

for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,4])
  except:
    pass
path="/home/shreyas/fresh_orange"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,5])
  except:
    pass
path="/home/shreyas/fresh_tomato"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,6])
  except:
    pass
path="/home/shreyas/stale_apple"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,7])
  except:
    pass
path="/home/shreyas/stale_banana"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,8])
  except:
    pass
path="/home/shreyas/stale_bitter_gourd"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,9])
  except:
    pass
path="/home/shreyas/stale_capsicum"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,10])
  except:
    pass
path="/home/shreyas/stale_orange"


for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,11])
  except:
    pass
path="/home/shreyas/stale_tomato"

for img in tqdm(os.listdir(path)):
  try:
    img_array=cv2.imread(os.path.join(path,img))
    img_array=remove(img_array)
    new_array=cv2.resize(img_array,resolution)
    training_data.append([new_array,12])
  except:
    pass

"""Making a list of all images(converted to arrays of numbers) and their labels as shown above

Actually labels can be only from 0 to 11 ,not 1 to 12 changed y-=1 in second notebook
"""

print(len(training_data))

"""The above dataset is not balanced ,since some category has just 300 images while some has more than 2000 ,thus we might have to pass weights while training the model to balance the dataset.

Also we have to shuffle the model otherwise it will first pass through all oranges and so on at a time
"""

import random
random.shuffle(training_data)
for i in range(1,10):

  print(training_data[i][1])

X=[]
y=[]
for i in training_data:
    X.append(i[0])
    y.append(i[1])
import numpy as np    
X=np.array(X).reshape(-1,45,45,3)   

print(X)



"""above ,we Converted image data to array form which will be used to train model """

import pickle
pickle_out=open("X.pickle","wb")
pickle.dump(X,pickle_out)
pickle_out.close()
pickle_out=open("y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()

"""Saving data as .pickle file

"""
